package View;

import static java.awt.event.KeyEvent.VK_ENTER;


/**
 *
 * @author chay
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        settings();
    }
    void settings(){
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BoxUsu = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        ses = new javax.swing.JButton();
        look = new javax.swing.JLabel();
        nolook = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 14)); // NOI18N
        jLabel2.setText("Iniciar sesión");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(312, 46, 91, 20);

        jLabel4.setFont(new java.awt.Font("Linux Libertine G", 1, 14)); // NOI18N
        jLabel4.setText("Nombre de usuario:");
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(73, 127, 150, 25);

        jLabel5.setFont(new java.awt.Font("Linux Libertine G", 1, 14)); // NOI18N
        jLabel5.setText("Contraseña:");
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 160, 150, 25);

        jLabel6.setFont(new java.awt.Font("MingLiU-ExtB", 1, 12)); // NOI18N
        jLabel6.setText("¿No tienes una cuenta?");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(258, 247, 139, 17);

        BoxUsu.setFont(new java.awt.Font("Rockwell", 0, 10)); // NOI18N
        BoxUsu.setPreferredSize(new java.awt.Dimension(500, 25));
        BoxUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxUsuActionPerformed(evt);
            }
        });
        BoxUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BoxUsuKeyReleased(evt);
            }
        });
        jPanel1.add(BoxUsu);
        BoxUsu.setBounds(229, 120, 357, 25);

        password.setFont(new java.awt.Font("Rockwell", 0, 10)); // NOI18N
        password.setPreferredSize(new java.awt.Dimension(500, 25));
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordKeyReleased(evt);
            }
        });
        jPanel1.add(password);
        password.setBounds(229, 160, 357, 25);

        jButton1.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton1.setText("Registrate aquí");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(404, 242, 118, 27);

        ses.setFont(new java.awt.Font("Rockwell", 0, 10)); // NOI18N
        ses.setText("Iniciar sesión");
        ses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sesActionPerformed(evt);
            }
        });
        jPanel1.add(ses);
        ses.setBounds(424, 200, 98, 24);

        look.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lookMouseClicked(evt);
            }
        });
        jPanel1.add(look);
        look.setBounds(600, 150, 21, 40);

        nolook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nolookMouseClicked(evt);
            }
        });
        jPanel1.add(nolook);
        nolook.setBounds(600, 150, 21, 40);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoxUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxUsuActionPerformed

    }//GEN-LAST:event_BoxUsuActionPerformed

    private void BoxUsuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BoxUsuKeyReleased
        char tec=evt.getKeyChar();
        if(tec==VK_ENTER){
            password.requestFocus();
        }
    }//GEN-LAST:event_BoxUsuKeyReleased

    private void passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyReleased
        char tec=evt.getKeyChar();
        if(tec==VK_ENTER){
            ses.doClick();
        }
    }//GEN-LAST:event_passwordKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       

    }//GEN-LAST:event_jButton1ActionPerformed

    private void sesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sesActionPerformed
        
    }//GEN-LAST:event_sesActionPerformed

    private void lookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lookMouseClicked
        look.setVisible(false);
        nolook.setVisible(true);
        password.setEchoChar((char) 0);
    }//GEN-LAST:event_lookMouseClicked

    private void nolookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nolookMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nolookMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField BoxUsu;
    public static javax.swing.JButton jButton1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel look;
    private javax.swing.JLabel nolook;
    public static javax.swing.JPasswordField password;
    public static javax.swing.JButton ses;
    // End of variables declaration//GEN-END:variables
}
